let curriculum={subjects:{}};let currentHTML='';
async function init(){curriculum=await (await fetch('curriculum.json')).json();for(let i=1;i<=8;i++){grade.innerHTML+=`<option>${i}</option>`;libGrade.innerHTML+=`<option>${i}</option>`;aGrade.innerHTML+=`<option>${i}</option>`;}Object.keys(curriculum.subjects).forEach(s=>{subject.innerHTML+=`<option>${s}</option>`;libSubject.innerHTML+=`<option>${s}</option>`;aSubject.innerHTML+=`<option>${s}</option>`});for(let i=1;i<=10;i++)week.innerHTML+=`<option>${i}</option>`;updateStrands();showLibrary();loadSettings();loadSaved();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(b.dataset.screen).classList.add('active');});
function openPlanner(type){document.querySelector('[data-screen="planner"]').click();planType.value=type}
function updateStrands(){strand.innerHTML=curriculum.subjects[subject.value].strands.map(x=>`<option>${x}</option>`).join('');showLibrary()}
subject.onchange=updateStrands;
function showLibrary(){if(!curriculum.subjects[libSubject.value])return;let s=curriculum.subjects[libSubject.value];libView.innerHTML=`<h3>${libSubject.value} — Grade ${libGrade.value}</h3><p><b>Strands:</b> ${s.strands.join(', ')}</p><p class="source">${s.source}</p><p><b>Planning chain:</b> Content Standard → Benchmark → Learning Objective → Learning Experiences → Assessment → Reflection.</p>`}
libSubject.onchange=showLibrary;libGrade.onchange=showLibrary;
function esc(x){return String(x||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function context(){return {planType:planType.value,grade:grade.value,subject:subject.value,strand:strand.value,term:term.value,week:week.value,year:year.value,duration:duration.value,topic:topic.value,language:language.value,instructions:instructions.value,teacher:teacher.value,school:school.value,province:province.value,district:district.value}}
async function generatePlan(){output.innerHTML='<div class="notice">⏳ Building plan…</div>';let c=context();let url=localStorage.serverUrl||'';if(url&&navigator.onLine){try{let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)});let j=await r.json();if(j.html){currentHTML=j.html;output.innerHTML=j.html;return}}catch(e){}}currentHTML=offlinePlan(c);output.innerHTML=currentHTML}
function offlinePlan(c){let source=curriculum.subjects[c.subject];let topic=c.topic||`${source.strands[0]} activity`;let head=`<h2>${c.planType.toUpperCase()} PLAN — Grade ${c.grade} ${c.subject}</h2><p><b>School:</b> ${esc(c.school)} &nbsp; <b>Teacher:</b> ${esc(c.teacher)} &nbsp; <b>Year:</b> ${c.year}</p><p><b>Strand:</b> ${esc(c.strand)} | <b>Topic:</b> ${esc(topic)} | <b>Language:</b> ${esc(c.language)}</p>`;
if(c.planType==='yearly')return head+`<table><tr><th>Term</th><th>Strand</th><th>Focus</th><th>Assessment</th></tr>${[1,2,3,4].map(t=>`<tr><td>Term ${t}</td><td>${esc(source.strands[(t-1)%source.strands.length])}</td><td>${esc(topic)} and related concepts</td><td>Class activities, practical task, quiz/test and portfolio</td></tr>`).join('')}</table>`;
if(c.planType==='termly')return head+`<table><tr><th>Week</th><th>Focus</th><th>Learning Objective</th><th>Assessment</th></tr>${Array.from({length:10},(_,i)=>`<tr><td>${i+1}</td><td>${esc(topic)}</td><td>Pupils explain, demonstrate and apply the key idea.</td><td>${i===9?'Term assessment':'Observation and class exercise'}</td></tr>`).join('')}</table>`;
if(c.planType==='weekly')return head+`<table><tr><th>Day</th><th>Focus</th><th>Activities</th><th>Assessment</th></tr>${['Monday','Tuesday','Wednesday','Thursday','Friday'].map((d,i)=>`<tr><td>${d}</td><td>${esc(topic)} — Part ${i+1}</td><td>Teacher modelling; pair/group activity; local examples; pupil presentation.</td><td>${i===4?'Weekly quiz':'Questioning and observation'}</td></tr>`).join('')}</table>`;
return head+`<h3>Learning Outcomes</h3><ul><li>Pupils explain the key idea in their own words.</li><li>Pupils demonstrate the skill through an activity.</li><li>Pupils complete the assessment task.</li></ul><h3>Knowledge, Skills, Attitudes & Values</h3><p>Knowledge of ${esc(topic)}; communication, observation, problem-solving and cooperation; respect for others and the local community.</p><h3>Teaching and Learning Materials</h3><p>Board, pictures/real objects, pupil books, locally available materials and activity sheet.</p><table><tr><th>Stage</th><th>Learning Experience</th></tr><tr><td>Introduction — 10 min</td><td>Greetings/roll, revise previous learning, introduce ${esc(topic)}, ask prior-knowledge questions.</td></tr><tr><td>Body — ${Math.max(10,+c.duration-20)} min</td><td>Teacher explanation and modelling; guided practice; group activity; pupil reporting and correction.</td></tr><tr><td>Conclusion — 10 min</td><td>Review key points, short assessment, feedback and homework.</td></tr></table><h3>Assessment</h3><p>Use observation, questioning and the completed pupil task against the learning indicators.</p><h3>Teacher Reflection</h3><p>______________________________________________________________</p><p><b>Teacher:</b> ____________________ &nbsp;&nbsp; <b>Head Teacher:</b> ____________________</p>`}
async function generateAssignment(){let c={grade:aGrade.value,subject:aSubject.value,topic:aTopic.value||'Selected topic',marks:aMarks.value,instructions:aInstructions.value};assignmentOut.innerHTML=`<h2>Assignment — Grade ${c.grade} ${c.subject}</h2><p><b>Topic:</b> ${esc(c.topic)} | <b>Total Marks:</b> ${c.marks}</p><ol>${Array.from({length:Math.min(10,Math.max(5,Math.floor(c.marks/2)))},(_,i)=>`<li>Answer the following question about <b>${esc(c.topic)}</b>. Use clear sentences and examples from your community. <span>(${Math.max(1,Math.floor(c.marks/10))} mark)</span></li>`).join('')}</ol><h3>Teacher Marking Guide</h3><p>Award marks for correct knowledge, relevant examples, clear communication and completion of the task. Adjust the guide to the verified grade-specific benchmark.</p>`}
function saveCurrent(){if(!currentHTML)return alert('Generate a plan first.');let a=JSON.parse(localStorage.sbcSaved||'[]');a.unshift({id:Date.now(),title:`${planType.value} — Grade ${grade.value} ${subject.value}`,html:currentHTML});localStorage.sbcSaved=JSON.stringify(a.slice(0,100));loadSaved();alert('Plan saved.')}
function loadSaved(){let a=JSON.parse(localStorage.sbcSaved||'[]');savedList.innerHTML=a.length?a.map(x=>`<div class="saved-item"><span>📄 ${esc(x.title)}</span><button onclick="viewSaved(${x.id})">View</button></div>`).join(''):'<p>No saved plans yet.</p>'}
function viewSaved(id){let x=JSON.parse(localStorage.sbcSaved||'[]').find(y=>y.id===id);currentHTML=x.html;output.innerHTML=x.html;document.querySelector('[data-screen="planner"]').click()}
async function downloadCurrent(){if(!currentHTML)return alert('Generate a plan first.');let name=`PNG_SBC_${planType.value}_Grade${grade.value}.doc`;let content=`<html><head><meta charset="UTF-8"><style>body{font-family:Arial}table{width:100%;border-collapse:collapse}th,td{border:1px solid #555;padding:6px}th{background:#e8f5ec}</style></head><body>${currentHTML}</body></html>`;if(window.desktopAPI)await window.desktopAPI.saveFile({defaultName:name,content,type:'doc'});else{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'application/msword'}));a.download=name;a.click()}}
function saveSettings(){localStorage.serverUrl=serverUrl.value.trim();localStorage.teacher=teacher.value;localStorage.school=school.value;localStorage.province=province.value;localStorage.district=district.value;alert('Settings saved.')}
function loadSettings(){teacher.value=localStorage.teacher||'';school.value=localStorage.school||'';province.value=localStorage.province||'';district.value=localStorage.district||'';serverUrl.value=localStorage.serverUrl||''}
init();